/**
 * Spec Generator — PRD → Technical Specification
 *
 * Implements the "PRD → Spec → Task Split → Code" pipeline from kstack article #15332.
 *
 * The spec is:
 *   1. Generated by LLM from a free-form requirement description
 *   2. Saved to .uagent/specs/YYYY-MM-DD-<slug>.md for version tracking
 *   3. Structured with: Overview, Design Decisions, Affected Files, Tasks, Risks
 *
 * Usage:
 *   CLI:  uagent spec "add JWT authentication middleware"
 *   REPL: /spec <description>
 *   Code: await generateSpec(description, projectRoot)
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { modelManager } from '../../models/model-manager.js';
import { loadProjectContext, loadRules } from '../context-loader.js';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SpecPhase {
  /** Phase number (1-based) */
  phase: number;
  /** Label, e.g. "Basic Scan" */
  label: string;
  /** Whether tasks within this phase can run in parallel */
  parallel: boolean;
  /** Phase IDs this phase depends on (must complete before this one starts) */
  dependsOn: number[];
  /** Tasks in this phase */
  tasks: string[];
  /** Optional task_ids for SpawnAgent context chaining */
  taskIds?: string[];
}

export interface SpecResult {
  /** Absolute path where the spec was saved */
  path: string;
  /** Full markdown content */
  content: string;
  /** Extracted task list (for follow-up automation) */
  tasks: string[];
  /** Affected files mentioned in the spec */
  affectedFiles: string[];
  /** Structured phase plan (for multi-agent orchestration) */
  phases: SpecPhase[];
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 50);
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function parseTasksFromSpec(content: string): string[] {
  const tasks: string[] = [];
  // Extract markdown task list items (- [ ] ... or numbered list in ## Tasks section)
  const taskSection = content.match(/##\s+(?:Tasks?|Implementation Steps?|工作项)[^\n]*([\s\S]*?)(?=\n##|\n---|\z)/i);
  if (taskSection) {
    const lines = taskSection[1].split('\n');
    for (const line of lines) {
      const match = line.match(/^\s*(?:-\s*\[[ x]\]|-|\d+\.)\s*(.+)/);
      if (match) tasks.push(match[1].trim());
    }
  }
  return tasks;
}

/**
 * Parse Phase structure from a spec that uses the Phase format.
 * Recognizes patterns like:
 *   ### Phase 1: Basic Scan (parallel)
 *   ### Phase 2: Deep Analysis (parallel, depends: Phase 1)
 */
function parsePhasesFromSpec(content: string): SpecPhase[] {
  const phases: SpecPhase[] = [];
  // Match Phase sections: ### Phase N: Label (parallel) or (sequential, depends: Phase M)
  const phasePattern = /###\s+Phase\s+(\d+)[:\s]+([^\n(]+)(?:\(([^)]*)\))?/gi;
  let match: RegExpExecArray | null;

  while ((match = phasePattern.exec(content)) !== null) {
    const phaseNum = parseInt(match[1], 10);
    const label = match[2].trim();
    const meta = (match[3] || '').toLowerCase();

    const isParallel = meta.includes('parallel');
    const dependsOn: number[] = [];
    const depMatch = meta.match(/depends?[\s:]+phase\s+(\d+(?:[,\s]+\d+)*)/i);
    if (depMatch) {
      depMatch[1].split(/[,\s]+/).forEach((n) => {
        const d = parseInt(n, 10);
        if (!isNaN(d)) dependsOn.push(d);
      });
    }

    // Find tasks within this phase block (up to the next ### Phase or ## section)
    const phaseStart = match.index + match[0].length;
    const nextPhaseMatch = /###\s+Phase\s+\d+|^##\s+/gim;
    nextPhaseMatch.lastIndex = phaseStart;
    const nextMatch = nextPhaseMatch.exec(content);
    const phaseBlock = content.slice(phaseStart, nextMatch ? nextMatch.index : undefined);

    const tasks: string[] = [];
    const taskIds: string[] = [];
    for (const line of phaseBlock.split('\n')) {
      const taskMatch = line.match(/^\s*(?:-\s*\[[ x]\]|-|\d+\.)\s*(.+)/);
      if (taskMatch) {
        const taskText = taskMatch[1].trim();
        tasks.push(taskText);
        // Extract optional task_id hint from annotations like <!-- id: my-task -->
        const idHint = line.match(/<!--\s*id:\s*([a-z0-9_-]+)\s*-->/i);
        taskIds.push(idHint ? idHint[1] : `phase${phaseNum}-task${tasks.length}`);
      }
    }

    phases.push({ phase: phaseNum, label, parallel: isParallel, dependsOn, tasks, taskIds });
  }

  return phases;
}

function parseAffectedFiles(content: string): string[] {
  const files: string[] = [];
  const fileSection = content.match(/##\s+(?:Affected Files?|涉及文件|Files?)[^\n]*([\s\S]*?)(?=\n##|\n---|\z)/i);
  if (fileSection) {
    const lines = fileSection[1].split('\n');
    for (const line of lines) {
      const match = line.match(/`([^`]+\.[a-zA-Z]{1,10})`|^\s*[-*]\s*(\S+\.[a-zA-Z]{1,10})/);
      if (match) files.push((match[1] || match[2]).trim());
    }
  }
  return files;
}

// ─── Prompt Builder ──────────────────────────────────────────────────────────

function buildSpecPrompt(description: string, projectCtx: string, rules: string): string {
  const projectSection = projectCtx
    ? `\n\n## Project Context\n${projectCtx}`
    : '';
  const rulesSection = rules
    ? `\n\n## Coding Rules (must be respected in the spec)\n${rules}`
    : '';

  return `You are a senior software architect. Generate a complete technical specification for the following requirement.

## Requirement
${description}
${projectSection}${rulesSection}

## Output Format (strict markdown, use these exact section headers)

# Spec: <short title>

**Date**: ${today()}
**Status**: Draft

## Overview
2-3 sentences describing what will be built and why.

## Design Decisions
- Decision 1: <choice and rationale>
- Decision 2: <choice and rationale>
(list 2-5 key design decisions)

## Affected Files
List every file that will be created or modified:
- \`path/to/file.ts\` — what changes
(use backtick paths so they can be parsed)

## Implementation Plan
Break the work into phases. Use this exact format so the phases can be parsed for parallel execution:

### Phase 1: <label> (parallel)
Independent tasks that can all run in parallel:
1. <specific task>
2. <specific task>

### Phase 2: <label> (parallel, depends: Phase 1)
Independent tasks, but must wait for Phase 1 to complete:
1. <specific task> <!-- id: phase2-task1 -->
2. <specific task>

### Phase 3: <label> (sequential, depends: Phase 1, Phase 2)
Tasks that depend on both previous phases:
1. <synthesis task>

Use (parallel) or (sequential) and depends: Phase N to express the dependency graph.
Aim for 2-4 phases with 2-5 tasks each.

## Risks & Mitigations
- Risk: <potential issue>
  Mitigation: <how to handle>
(2-4 risks)

## Testing
How to verify the implementation is correct.

---
Generate the spec now. Be concrete, not vague. Reference actual files from the project if known.`;
}

// ─── Main Export ─────────────────────────────────────────────────────────────

/**
 * Generate a technical specification from a requirement description.
 *
 * @param description  Free-form requirement text (like a PRD)
 * @param projectRoot  Project root directory (defaults to cwd)
 * @returns            SpecResult with path, content, tasks, affectedFiles
 */
export async function generateSpec(
  description: string,
  projectRoot?: string,
): Promise<SpecResult> {
  const root = resolve(projectRoot ?? process.cwd());
  const specsDir = join(root, '.uagent', 'specs');
  mkdirSync(specsDir, { recursive: true, mode: 0o755 });

  // Load project context (AGENTS.md, rules) to ground the spec
  const ctx = loadProjectContext(root);
  const rules = loadRules(root);

  const prompt = buildSpecPrompt(description, ctx.instructions, rules.content);

  // Use the 'main' model for spec generation (high quality needed)
  const client = modelManager.getClient('main');
  const response = await client.chat({
    systemPrompt:
      'You are a senior software architect. Generate precise, actionable technical specifications. ' +
      'Always use the exact section headers specified. Never skip sections.',
    messages: [{ role: 'user', content: prompt }],
  });

  const content = response.content.trim();
  const tasks = parseTasksFromSpec(content);
  const affectedFiles = parseAffectedFiles(content);
  const phases = parsePhasesFromSpec(content);

  // Save to .uagent/specs/YYYY-MM-DD-<slug>.md
  const slug = slugify(description);
  const fileName = `${today()}-${slug}.md`;
  const filePath = join(specsDir, fileName);
  writeFileSync(filePath, content, { encoding: 'utf8', mode: 0o644 });

  return { path: filePath, content, tasks, affectedFiles, phases };
}

/**
 * List all existing specs for the current project.
 */
export function listSpecs(projectRoot?: string): Array<{ name: string; path: string; date: string }> {
  const root = resolve(projectRoot ?? process.cwd());
  const specsDir = join(root, '.uagent', 'specs');
  if (!existsSync(specsDir)) return [];

  return readdirSync(specsDir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .reverse() // newest first
    .map((f) => ({
      name: f.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.md$/, ''),
      path: join(specsDir, f),
      date: f.slice(0, 10),
    }));
}

/**
 * Read a spec file by index (0 = most recent) or by filename.
 */
export function readSpec(indexOrName: number | string, projectRoot?: string): string | null {
  const specs = listSpecs(projectRoot);
  if (specs.length === 0) return null;
  if (typeof indexOrName === 'number') {
    return specs[indexOrName] ? readFileSync(specs[indexOrName].path, 'utf8') : null;
  }
  const found = specs.find((s) => s.name.includes(indexOrName) || s.path.includes(indexOrName));
  return found ? readFileSync(found.path, 'utf8') : null;
}
