/**
 * Spec Generator — PRD → Technical Specification
 *
 * Implements the "PRD → Spec → Task Split → Code" pipeline from kstack article #15332.
 *
 * The spec is:
 *   1. Generated by LLM from a free-form requirement description
 *   2. Saved to .uagent/specs/YYYY-MM-DD-<slug>.md for version tracking
 *   3. Structured with: Overview, Design Decisions, Affected Files, Tasks, Risks
 *
 * Usage:
 *   CLI:  uagent spec "add JWT authentication middleware"
 *   REPL: /spec <description>
 *   Code: await generateSpec(description, projectRoot)
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { modelManager } from '../../models/model-manager.js';
import { loadProjectContext, loadRules } from '../context-loader.js';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SpecResult {
  /** Absolute path where the spec was saved */
  path: string;
  /** Full markdown content */
  content: string;
  /** Extracted task list (for follow-up automation) */
  tasks: string[];
  /** Affected files mentioned in the spec */
  affectedFiles: string[];
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 50);
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function parseTasksFromSpec(content: string): string[] {
  const tasks: string[] = [];
  // Extract markdown task list items (- [ ] ... or numbered list in ## Tasks section)
  const taskSection = content.match(/##\s+(?:Tasks?|Implementation Steps?|工作项)[^\n]*([\s\S]*?)(?=\n##|\n---|\z)/i);
  if (taskSection) {
    const lines = taskSection[1].split('\n');
    for (const line of lines) {
      const match = line.match(/^\s*(?:-\s*\[[ x]\]|-|\d+\.)\s*(.+)/);
      if (match) tasks.push(match[1].trim());
    }
  }
  return tasks;
}

function parseAffectedFiles(content: string): string[] {
  const files: string[] = [];
  const fileSection = content.match(/##\s+(?:Affected Files?|涉及文件|Files?)[^\n]*([\s\S]*?)(?=\n##|\n---|\z)/i);
  if (fileSection) {
    const lines = fileSection[1].split('\n');
    for (const line of lines) {
      const match = line.match(/`([^`]+\.[a-zA-Z]{1,10})`|^\s*[-*]\s*(\S+\.[a-zA-Z]{1,10})/);
      if (match) files.push((match[1] || match[2]).trim());
    }
  }
  return files;
}

// ─── Prompt Builder ──────────────────────────────────────────────────────────

function buildSpecPrompt(description: string, projectCtx: string, rules: string): string {
  const projectSection = projectCtx
    ? `\n\n## Project Context\n${projectCtx}`
    : '';
  const rulesSection = rules
    ? `\n\n## Coding Rules (must be respected in the spec)\n${rules}`
    : '';

  return `You are a senior software architect. Generate a complete technical specification for the following requirement.

## Requirement
${description}
${projectSection}${rulesSection}

## Output Format (strict markdown, use these exact section headers)

# Spec: <short title>

**Date**: ${today()}
**Status**: Draft

## Overview
2-3 sentences describing what will be built and why.

## Design Decisions
- Decision 1: <choice and rationale>
- Decision 2: <choice and rationale>
(list 2-5 key design decisions)

## Affected Files
List every file that will be created or modified:
- \`path/to/file.ts\` — what changes
(use backtick paths so they can be parsed)

## Tasks
Numbered implementation steps (atomic, each completable by AI in one pass):
1. <concrete task — be specific about file/function/method>
2. <concrete task>
(5-10 tasks total)

## Risks & Mitigations
- Risk: <potential issue>
  Mitigation: <how to handle>
(2-4 risks)

## Testing
How to verify the implementation is correct.

---
Generate the spec now. Be concrete, not vague. Reference actual files from the project if known.`;
}

// ─── Main Export ─────────────────────────────────────────────────────────────

/**
 * Generate a technical specification from a requirement description.
 *
 * @param description  Free-form requirement text (like a PRD)
 * @param projectRoot  Project root directory (defaults to cwd)
 * @returns            SpecResult with path, content, tasks, affectedFiles
 */
export async function generateSpec(
  description: string,
  projectRoot?: string,
): Promise<SpecResult> {
  const root = resolve(projectRoot ?? process.cwd());
  const specsDir = join(root, '.uagent', 'specs');
  mkdirSync(specsDir, { recursive: true, mode: 0o755 });

  // Load project context (AGENTS.md, rules) to ground the spec
  const ctx = loadProjectContext(root);
  const rules = loadRules(root);

  const prompt = buildSpecPrompt(description, ctx.instructions, rules.content);

  // Use the 'main' model for spec generation (high quality needed)
  const client = modelManager.getClient('main');
  const response = await client.chat({
    systemPrompt:
      'You are a senior software architect. Generate precise, actionable technical specifications. ' +
      'Always use the exact section headers specified. Never skip sections.',
    messages: [{ role: 'user', content: prompt }],
  });

  const content = response.content.trim();
  const tasks = parseTasksFromSpec(content);
  const affectedFiles = parseAffectedFiles(content);

  // Save to .uagent/specs/YYYY-MM-DD-<slug>.md
  const slug = slugify(description);
  const fileName = `${today()}-${slug}.md`;
  const filePath = join(specsDir, fileName);
  writeFileSync(filePath, content, { encoding: 'utf8', mode: 0o644 });

  return { path: filePath, content, tasks, affectedFiles };
}

/**
 * List all existing specs for the current project.
 */
export function listSpecs(projectRoot?: string): Array<{ name: string; path: string; date: string }> {
  const root = resolve(projectRoot ?? process.cwd());
  const specsDir = join(root, '.uagent', 'specs');
  if (!existsSync(specsDir)) return [];

  return readdirSync(specsDir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .reverse() // newest first
    .map((f) => ({
      name: f.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.md$/, ''),
      path: join(specsDir, f),
      date: f.slice(0, 10),
    }));
}

/**
 * Read a spec file by index (0 = most recent) or by filename.
 */
export function readSpec(indexOrName: number | string, projectRoot?: string): string | null {
  const specs = listSpecs(projectRoot);
  if (specs.length === 0) return null;
  if (typeof indexOrName === 'number') {
    return specs[indexOrName] ? readFileSync(specs[indexOrName].path, 'utf8') : null;
  }
  const found = specs.find((s) => s.name.includes(indexOrName) || s.path.includes(indexOrName));
  return found ? readFileSync(found.path, 'utf8') : null;
}
