/**
 * Spec Generator — PRD → Technical Specification
 *
 * Implements the "PRD → Spec → Task Split → Code" pipeline from kstack article #15332.
 * Enhanced with PM-perspective defect review (5 dimensions: B/U/O/D/R) and
 * 29-item document quality check inspired by kstack article #15344
 * ("2W行代码的需求AI怎么写：从1个PRD到7个独立文档").
 *
 * The spec is:
 *   1. Generated by LLM from a free-form requirement description
 *   2. Reviewed by LLM from a PM perspective (B/U/O/D/R defect categories)
 *   3. Quality-checked against 29 completeness/consistency/feasibility items
 *   4. Issues annotated inline — never block output (标注不阻塞原则)
 *   5. Saved to .uagent/specs/YYYY-MM-DD-<slug>.md for version tracking
 *
 * Usage:
 *   CLI:  uagent spec "add JWT authentication middleware"
 *   REPL: /spec <description>
 *   Code: await generateSpec(description, projectRoot)
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'fs';
import { join, resolve } from 'path';
import { modelManager } from '../../models/model-manager.js';
import { loadProjectContext, loadRules } from '../context-loader.js';

// ─── Types ───────────────────────────────────────────────────────────────────

export interface SpecPhase {
  /** Phase number (1-based) */
  phase: number;
  /** Label, e.g. "Basic Scan" */
  label: string;
  /** Whether tasks within this phase can run in parallel */
  parallel: boolean;
  /** Phase IDs this phase depends on (must complete before this one starts) */
  dependsOn: number[];
  /** Tasks in this phase */
  tasks: string[];
  /** Optional task_ids for SpawnAgent context chaining */
  taskIds?: string[];
}

export interface SpecResult {
  /** Absolute path where the spec was saved */
  path: string;
  /** Full markdown content (spec + PM review + quality check appended) */
  content: string;
  /** Extracted task list (for follow-up automation) */
  tasks: string[];
  /** Affected files mentioned in the spec */
  affectedFiles: string[];
  /** Structured phase plan (for multi-agent orchestration) */
  phases: SpecPhase[];
  /** PM-perspective defect review summary */
  pmReview?: {
    defects: { p0: number; p1: number; p2: number; total: number };
    content: string;
  };
  /** 29-item document quality check summary */
  qualityCheck?: {
    passed: number;
    failP0: number;
    grade: string;
    content: string;
  };
}

// ─── Helpers ─────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^\w\s-]/g, '')
    .replace(/\s+/g, '-')
    .slice(0, 50);
}

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function parseTasksFromSpec(content: string): string[] {
  const tasks: string[] = [];
  // Extract markdown task list items (- [ ] ... or numbered list in ## Tasks section)
  const taskSection = content.match(/##\s+(?:Tasks?|Implementation Steps?|工作项)[^\n]*([\s\S]*?)(?=\n##|\n---|\z)/i);
  if (taskSection) {
    const lines = taskSection[1].split('\n');
    for (const line of lines) {
      const match = line.match(/^\s*(?:-\s*\[[ x]\]|-|\d+\.)\s*(.+)/);
      if (match) tasks.push(match[1].trim());
    }
  }
  return tasks;
}

/**
 * Parse Phase structure from a spec that uses the Phase format.
 * Recognizes patterns like:
 *   ### Phase 1: Basic Scan (parallel)
 *   ### Phase 2: Deep Analysis (parallel, depends: Phase 1)
 */
function parsePhasesFromSpec(content: string): SpecPhase[] {
  const phases: SpecPhase[] = [];
  // Match Phase sections: ### Phase N: Label (parallel) or (sequential, depends: Phase M)
  const phasePattern = /###\s+Phase\s+(\d+)[:\s]+([^\n(]+)(?:\(([^)]*)\))?/gi;
  let match: RegExpExecArray | null;

  while ((match = phasePattern.exec(content)) !== null) {
    const phaseNum = parseInt(match[1], 10);
    const label = match[2].trim();
    const meta = (match[3] || '').toLowerCase();

    const isParallel = meta.includes('parallel');
    const dependsOn: number[] = [];
    const depMatch = meta.match(/depends?[\s:]+phase\s+(\d+(?:[,\s]+\d+)*)/i);
    if (depMatch) {
      depMatch[1].split(/[,\s]+/).forEach((n) => {
        const d = parseInt(n, 10);
        if (!isNaN(d)) dependsOn.push(d);
      });
    }

    // Find tasks within this phase block (up to the next ### Phase or ## section)
    const phaseStart = match.index + match[0].length;
    const nextPhaseMatch = /###\s+Phase\s+\d+|^##\s+/gim;
    nextPhaseMatch.lastIndex = phaseStart;
    const nextMatch = nextPhaseMatch.exec(content);
    const phaseBlock = content.slice(phaseStart, nextMatch ? nextMatch.index : undefined);

    const tasks: string[] = [];
    const taskIds: string[] = [];
    for (const line of phaseBlock.split('\n')) {
      const taskMatch = line.match(/^\s*(?:-\s*\[[ x]\]|-|\d+\.)\s*(.+)/);
      if (taskMatch) {
        const taskText = taskMatch[1].trim();
        tasks.push(taskText);
        // Extract optional task_id hint from annotations like <!-- id: my-task -->
        const idHint = line.match(/<!--\s*id:\s*([a-z0-9_-]+)\s*-->/i);
        taskIds.push(idHint ? idHint[1] : `phase${phaseNum}-task${tasks.length}`);
      }
    }

    phases.push({ phase: phaseNum, label, parallel: isParallel, dependsOn, tasks, taskIds });
  }

  return phases;
}

function parseAffectedFiles(content: string): string[] {
  const files: string[] = [];
  const fileSection = content.match(/##\s+(?:Affected Files?|涉及文件|Files?)[^\n]*([\s\S]*?)(?=\n##|\n---|\z)/i);
  if (fileSection) {
    const lines = fileSection[1].split('\n');
    for (const line of lines) {
      const match = line.match(/`([^`]+\.[a-zA-Z]{1,10})`|^\s*[-*]\s*(\S+\.[a-zA-Z]{1,10})/);
      if (match) files.push((match[1] || match[2]).trim());
    }
  }
  return files;
}

// ─── PM Review ───────────────────────────────────────────────────────────────

/**
 * PM-perspective defect review prompt.
 * Checks the spec across 5 dimensions from kstack article #15344:
 *   B - Business Logic defects
 *   U - UX defects
 *   O - Operational configuration defects
 *   D - Data / analytics defects
 *   R - Risk & compliance defects
 *
 * Follows the "标注不阻塞" principle: issues are annotated inline, never block output.
 */
function buildPmReviewPrompt(specContent: string, originalDescription: string): string {
  return `You are a 10-year veteran product manager specializing in software systems. Review the technical specification below for PRD defects.

## Original Requirement
${originalDescription}

## Technical Specification to Review
${specContent}

## Your Task
Review the spec from a PM perspective across 5 dimensions. Find defects and gaps that will cause problems during development or testing.

For each defect found, output in this exact format:
\`\`\`
🔴 <Category><N> [<Priority>] <Short title>
Problem: <What's missing or wrong>
Impact: <What will happen if not addressed>
Suggestion: <What to add or clarify>
\`\`\`

Where:
- Category: B (Business Logic), U (UX), O (Operational), D (Data/Analytics), R (Risk/Compliance)
- Priority: P0 (blocks development), P1 (important gap), P2 (nice to have)
- N: sequential number within category (B001, B002, U001, etc.)

## Review Dimensions

**B — Business Logic Defects**
- Are all state transitions documented? Are there gaps in the state machine?
- Are edge cases and fallback logic specified? (e.g., what happens when a user is deleted?)
- Are permission boundaries clear for each role?
- Are business rules complete and unambiguous?
- Is data consistency guaranteed across operations?

**U — UX Defects**
- Are loading/empty/error states defined for all UI components?
- Is error feedback specified (what message does the user see)?
- Are confirmation dialogs / destructive action warnings specified?
- Are form validation rules documented?

**O — Operational Defects**
- Are configuration parameters flexible enough?
- Is configuration validation specified?
- Can configurations be rolled back safely?
- Is the impact scope of configuration changes documented?

**D — Data/Analytics Defects**
- Are key metrics defined and measurable?
- Is data ownership and lineage clear?
- Are there data retention or archiving policies?

**R — Risk/Compliance Defects**
- Are there financial, security, or data privacy risks?
- Is audit logging specified for sensitive operations?
- Are there regulatory compliance requirements to address?

## Output

First, list all defects found (use the format above).
Then output a summary table:
| Category | P0 | P1 | P2 | Total |
| B — Business | N | N | N | N |
| U — UX | N | N | N | N |
| O — Operational | N | N | N | N |
| D — Data | N | N | N | N |
| R — Risk | N | N | N | N |
| **Total** | N | N | N | N |

Then list up to 5 "Pending Confirmation" items that require the requester to clarify before development starts.

Be thorough. A defect found now costs 10x less than one found in testing.`;
}

/**
 * 29-item document quality check.
 * Adapted from kstack article #15344 Stage 5 quality detection.
 * Issues are annotated as ISSUE-XXX inline — never block output.
 */
function buildQualityCheckPrompt(specContent: string): string {
  return `You are a technical documentation quality inspector. Check the following technical specification against a 29-item quality checklist.

## Specification to Check
${specContent}

## Quality Checklist (29 items)

### Completeness (9 items)
C1. Module/feature goal is clearly stated
C2. Complete feature list with priorities
C3. Core entities/models defined
C4. Enum/constant values documented
C5. Database/storage schema provided (where relevant)
C6. API interface signatures defined (where relevant)
C7. Business rules explicitly stated
C8. Edge/boundary conditions listed
C9. Acceptance criteria defined

### Consistency (5 items)
C10. Entities match between schema and API definitions
C11. API parameter types match entity definitions
C12. Enum values used consistently throughout
C13. Business rules have no contradictions
C14. Naming style is consistent (camelCase, snake_case, etc.)

### Feasibility (5 items)
C15. Technology choices are compatible with project stack
C16. External API dependencies are identified
C17. Data model is feasible (no circular deps, correct cardinality)
C18. Performance considerations addressed for scale
C19. All dependencies and prerequisites identified

### Boundary Coverage (5 items)
C20. Input boundary conditions documented (null, empty, max length)
C21. State boundary transitions all covered
C22. Concurrent access / race conditions considered
C23. Time boundary cases handled (timezone, DST, expiry)
C24. Data volume boundary addressed

### Contract Completeness (5 items)
C25. External interfaces (APIs) fully specified
C26. Internal interfaces between modules specified
C27. Third-party dependency contracts documented
C28. Data contracts (request/response schemas) complete
C29. Event/message contracts defined (if async)

## Output Format

For each FAILED item, output:
\`ISSUE-<NNN> | <Item ID> | <Priority: P0/P1/P2> | <Short description> | <Fix suggestion>\`

Example:
\`ISSUE-001 | C1.3 | P0 | Entity definitions missing for WorkOrder | Add entity schema with all fields and types\`

Then output the quality score:
- Passed: N/29
- Failed P0: N
- Failed P1: N
- Failed P2: N
- Overall quality: PASS (≥24/29, zero P0) | WARN (≥20/29, ≤2 P0) | FAIL (<20/29 or >2 P0)

Keep it concise. Only list failed items.`;
}

/**
 * Parse PM review output to extract defect count by priority.
 */
function parsePmReviewSummary(reviewContent: string): { p0: number; p1: number; p2: number; total: number } {
  const p0 = (reviewContent.match(/\[P0\]/g) || []).length;
  const p1 = (reviewContent.match(/\[P1\]/g) || []).length;
  const p2 = (reviewContent.match(/\[P2\]/g) || []).length;
  return { p0, p1, p2, total: p0 + p1 + p2 };
}

/**
 * Parse quality check output to extract issue count.
 */
function parseQualityScore(qualityContent: string): { passed: number; failP0: number; grade: string } {
  const passedMatch = qualityContent.match(/Passed:\s*(\d+)\/29/);
  const p0Match = qualityContent.match(/Failed P0:\s*(\d+)/);
  const gradeMatch = qualityContent.match(/Overall quality:\s*(PASS|WARN|FAIL)/);
  return {
    passed: passedMatch ? parseInt(passedMatch[1], 10) : 0,
    failP0: p0Match ? parseInt(p0Match[1], 10) : 0,
    grade: gradeMatch ? gradeMatch[1] : 'UNKNOWN',
  };
}

// ─── Prompt Builder ──────────────────────────────────────────────────────────

function buildSpecPrompt(description: string, projectCtx: string, rules: string): string {
  const projectSection = projectCtx
    ? `\n\n## Project Context\n${projectCtx}`
    : '';
  const rulesSection = rules
    ? `\n\n## Coding Rules (must be respected in the spec)\n${rules}`
    : '';

  return `You are a senior software architect. Generate a complete technical specification for the following requirement.

## Requirement
${description}
${projectSection}${rulesSection}

## Output Format (strict markdown, use these exact section headers)

# Spec: <short title>

**Date**: ${today()}
**Status**: Draft

## Overview
2-3 sentences describing what will be built and why.

## Design Decisions
- Decision 1: <choice and rationale>
- Decision 2: <choice and rationale>
(list 2-5 key design decisions)

## Affected Files
List every file that will be created or modified:
- \`path/to/file.ts\` — what changes
(use backtick paths so they can be parsed)

## Implementation Plan
Break the work into phases. Use this exact format so the phases can be parsed for parallel execution:

### Phase 1: <label> (parallel)
Independent tasks that can all run in parallel:
1. <specific task>
2. <specific task>

### Phase 2: <label> (parallel, depends: Phase 1)
Independent tasks, but must wait for Phase 1 to complete:
1. <specific task> <!-- id: phase2-task1 -->
2. <specific task>

### Phase 3: <label> (sequential, depends: Phase 1, Phase 2)
Tasks that depend on both previous phases:
1. <synthesis task>

Use (parallel) or (sequential) and depends: Phase N to express the dependency graph.
Aim for 2-4 phases with 2-5 tasks each.

## Risks & Mitigations
- Risk: <potential issue>
  Mitigation: <how to handle>
(2-4 risks)

## Testing
How to verify the implementation is correct.

---
Generate the spec now. Be concrete, not vague. Reference actual files from the project if known.`;
}

// ─── Main Export ─────────────────────────────────────────────────────────────

/**
 * Generate a technical specification from a requirement description.
 *
 * Pipeline (from kstack article #15344):
 *   Stage 1: Generate spec from requirement (senior architect perspective)
 *   Stage 2: PM-perspective defect review (B/U/O/D/R — 5 dimensions)
 *   Stage 3: 29-item document quality check (completeness/consistency/feasibility)
 *   Stage 4: Append review + quality results inline; save final spec
 *
 * Key principle: "标注不阻塞" — issues are annotated, never block output.
 *
 * @param description  Free-form requirement text (like a PRD)
 * @param projectRoot  Project root directory (defaults to cwd)
 * @param opts         Options: skip PM review or quality check for fast mode
 * @returns            SpecResult with path, content, tasks, affectedFiles, pmReview, qualityCheck
 */
export async function generateSpec(
  description: string,
  projectRoot?: string,
  opts: { skipPmReview?: boolean; skipQualityCheck?: boolean } = {},
): Promise<SpecResult> {
  const root = resolve(projectRoot ?? process.cwd());
  const specsDir = join(root, '.uagent', 'specs');
  mkdirSync(specsDir, { recursive: true, mode: 0o755 });

  // Load project context (AGENTS.md, rules) to ground the spec
  const ctx = loadProjectContext(root);
  const rules = loadRules(root);

  const prompt = buildSpecPrompt(description, ctx.instructions, rules.content);

  // ── Stage 1: Generate spec ────────────────────────────────────────────────
  const client = modelManager.getClient('main');
  const specResponse = await client.chat({
    systemPrompt:
      'You are a senior software architect. Generate precise, actionable technical specifications. ' +
      'Always use the exact section headers specified. Never skip sections.',
    messages: [{ role: 'user', content: prompt }],
  });

  const specContent = specResponse.content.trim();

  // ── Stage 2: PM-perspective defect review (5 dimensions: B/U/O/D/R) ──────
  // Runs in parallel with Stage 3 to minimize wall-clock time.
  // "标注不阻塞" — failures here never block saving the spec.
  let pmReviewContent = '';
  let qualityContent = '';
  let finalSpecContent = specContent; // may be revised by Actor-Critic loop below
  let actorCriticTrace = ''; // records whether a revision was triggered

  if (!opts.skipPmReview && !opts.skipQualityCheck) {
    // Run both reviews in parallel
    const [pmResult, qualityResult] = await Promise.allSettled([
      client.chat({
        systemPrompt:
          'You are a 10-year veteran product manager. Be thorough and critical. ' +
          'Find every gap that could cause development or testing problems.',
        messages: [{ role: 'user', content: buildPmReviewPrompt(specContent, description) }],
      }),
      client.chat({
        systemPrompt:
          'You are a technical documentation quality inspector. Be precise and concise. ' +
          'Only list failed items.',
        messages: [{ role: 'user', content: buildQualityCheckPrompt(specContent) }],
      }),
    ]);

    if (pmResult.status === 'fulfilled') pmReviewContent = pmResult.value.content.trim();
    if (qualityResult.status === 'fulfilled') qualityContent = qualityResult.value.content.trim();
  } else {
    if (!opts.skipPmReview) {
      try {
        const r = await client.chat({
          systemPrompt: 'You are a 10-year veteran product manager.',
          messages: [{ role: 'user', content: buildPmReviewPrompt(specContent, description) }],
        });
        pmReviewContent = r.content.trim();
      } catch { /* annotate-not-block */ }
    }
    if (!opts.skipQualityCheck) {
      try {
        const r = await client.chat({
          systemPrompt: 'You are a technical documentation quality inspector.',
          messages: [{ role: 'user', content: buildQualityCheckPrompt(specContent) }],
        });
        qualityContent = r.content.trim();
      } catch { /* annotate-not-block */ }
    }
  }

  // ── Stage 2.5: Actor-Critic Revision Loop (Cowork Forge pattern) ──────────
  // Inspired by Cowork Forge's Actor-Critic: "每个阶段不是生成即结束，而是生成→审查→迭代"
  // If PM review found P0 defects, run ONE revision pass where the Actor (LLM)
  // rewrites the spec with the PM review feedback injected.
  // Capped at 1 iteration to prevent infinite loops.
  if (pmReviewContent && !opts.skipPmReview) {
    const initialDefects = parsePmReviewSummary(pmReviewContent);
    if (initialDefects.p0 > 0) {
      try {
        const revisionPrompt = [
          `You are a senior software architect. You previously wrote a technical specification,`,
          `but a PM review found ${initialDefects.p0} P0 defects that MUST be fixed before development starts.`,
          ``,
          `## Original Requirement`,
          description,
          ``,
          `## PM Review Feedback (P0 defects to address)`,
          pmReviewContent,
          ``,
          `## Current Spec (to be revised)`,
          specContent,
          ``,
          `## Your Task`,
          `Revise the spec to address ALL P0 defects from the PM review above.`,
          `Keep the same section structure. Be concrete and specific.`,
          `Output ONLY the revised spec (no prose, no preamble).`,
        ].join('\n');

        const revisionResponse = await client.chat({
          systemPrompt:
            'You are a senior software architect revising a spec based on PM review feedback. ' +
            'Address all P0 defects. Keep the same structure. Output only the revised spec.',
          messages: [{ role: 'user', content: revisionPrompt }],
        });

        const revisedContent = revisionResponse.content.trim();
        if (revisedContent && revisedContent.length > 100) {
          finalSpecContent = revisedContent;

          // Re-run PM review on the revised spec (non-blocking)
          // to track whether revision actually fixed the P0s
          try {
            const reReview = await client.chat({
              systemPrompt: 'You are a 10-year veteran product manager. Be thorough and critical.',
              messages: [{ role: 'user', content: buildPmReviewPrompt(revisedContent, description) }],
            });
            const revisedReviewContent = reReview.content.trim();
            const revisedDefects = parsePmReviewSummary(revisedReviewContent);

            actorCriticTrace = [
              `## Actor-Critic Revision Trace`,
              ``,
              `> **Pattern**: Cowork Forge Actor-Critic ("生成→审查→迭代")`,
              `> **Trigger**: PM Review found ${initialDefects.p0} P0 defect(s)`,
              `> **Action**: Actor (LLM) revised spec in response to Critic (PM Review) feedback`,
              `> **Result**: Post-revision P0 count: ${revisedDefects.p0} (was: ${initialDefects.p0})`,
              ``,
              `### Pre-Revision Defects`,
              `P0: ${initialDefects.p0} | P1: ${initialDefects.p1} | P2: ${initialDefects.p2}`,
              ``,
              `### Post-Revision Defects`,
              `P0: ${revisedDefects.p0} | P1: ${revisedDefects.p1} | P2: ${revisedDefects.p2}`,
            ].join('\n');

            // Use post-revision review as the canonical PM review
            pmReviewContent = revisedReviewContent;
          } catch {
            actorCriticTrace = [
              `## Actor-Critic Revision Trace`,
              `> **Trigger**: PM Review found ${initialDefects.p0} P0 defect(s) — spec revised.`,
              `> **Re-review**: Failed (non-fatal). Revision was applied.`,
            ].join('\n');
          }
        }
      } catch {
        // Actor-Critic revision failure is non-fatal — proceed with original spec
        actorCriticTrace = `## Actor-Critic Revision Trace\n> Revision attempted but failed (non-fatal). Original spec retained.`;
      }
    }
  }

  // ── Stage 3: Parse results ────────────────────────────────────────────────
  const tasks = parseTasksFromSpec(specContent);
  const affectedFiles = parseAffectedFiles(specContent);
  const phases = parsePhasesFromSpec(specContent);

  const pmReview = pmReviewContent
    ? { defects: parsePmReviewSummary(pmReviewContent), content: pmReviewContent }
    : undefined;

  const qualityCheck = qualityContent
    ? { ...parseQualityScore(qualityContent), content: qualityContent }
    : undefined;

  // ── Stage 4: Assemble final document (spec + reviews appended inline) ─────
  // Use finalSpecContent (may be the Actor-Critic revised version)
  const sections: string[] = [finalSpecContent];

  // If Actor-Critic revised the spec, append the trace for transparency
  if (actorCriticTrace) {
    sections.push(`\n\n---\n\n${actorCriticTrace}`);
  }

  if (pmReviewContent) {
    const summary = pmReview!.defects;
    sections.push(
      `\n---\n\n## PM Review (B/U/O/D/R Defect Analysis)\n\n` +
      `> **Summary**: ${summary.total} defects found — P0: ${summary.p0}, P1: ${summary.p1}, P2: ${summary.p2}\n` +
      `> Issues are annotated below. Address P0 items before starting development.\n\n` +
      pmReviewContent,
    );
  }

  if (qualityContent) {
    const qc = qualityCheck!;
    const gradeEmoji = qc.grade === 'PASS' ? '✅' : qc.grade === 'WARN' ? '⚠️' : '❌';
    sections.push(
      `\n---\n\n## Document Quality Check (29-item)\n\n` +
      `> **Score**: ${qc.passed}/29 — Overall: ${gradeEmoji} ${qc.grade}` +
      (qc.failP0 > 0 ? ` | ⚠️ ${qc.failP0} P0 issues require immediate attention` : '') +
      `\n\n` +
      qualityContent,
    );
  }

  const finalContent = sections.join('');

  // Save to .uagent/specs/YYYY-MM-DD-<slug>.md
  const slug = slugify(description);
  const fileName = `${today()}-${slug}.md`;
  const filePath = join(specsDir, fileName);
  writeFileSync(filePath, finalContent, { encoding: 'utf8', mode: 0o644 });

  return { path: filePath, content: finalContent, tasks, affectedFiles, phases, pmReview, qualityCheck };
}

/**
 * List all existing specs for the current project.
 */
export function listSpecs(projectRoot?: string): Array<{ name: string; path: string; date: string }> {
  const root = resolve(projectRoot ?? process.cwd());
  const specsDir = join(root, '.uagent', 'specs');
  if (!existsSync(specsDir)) return [];

  return readdirSync(specsDir)
    .filter((f) => f.endsWith('.md'))
    .sort()
    .reverse() // newest first
    .map((f) => ({
      name: f.replace(/^\d{4}-\d{2}-\d{2}-/, '').replace(/\.md$/, ''),
      path: join(specsDir, f),
      date: f.slice(0, 10),
    }));
}

/**
 * Read a spec file by index (0 = most recent) or by filename.
 */
export function readSpec(indexOrName: number | string, projectRoot?: string): string | null {
  const specs = listSpecs(projectRoot);
  if (specs.length === 0) return null;
  if (typeof indexOrName === 'number') {
    return specs[indexOrName] ? readFileSync(specs[indexOrName].path, 'utf8') : null;
  }
  const found = specs.find((s) => s.name.includes(indexOrName) || s.path.includes(indexOrName));
  return found ? readFileSync(found.path, 'utf8') : null;
}
